/// Countries offered on Create Account. Ghana is first (home market).
const kRegisterCountries = <String>[
  'Ghana',
  'Nigeria',
  'Togo',
  'Benin',
  "Côte d'Ivoire",
  'Burkina Faso',
  'Mali',
  'Senegal',
  'Liberia',
  'Sierra Leone',
  'Guinea',
  'Gambia',
  'Cameroon',
  'Kenya',
  'Uganda',
  'Tanzania',
  'Rwanda',
  'South Africa',
  'Egypt',
  'Morocco',
  'Algeria',
  'Tunisia',
  'Ethiopia',
  'Zimbabwe',
  'Zambia',
  'Botswana',
  'Namibia',
  'Mozambique',
  'Angola',
  'Democratic Republic of the Congo',
  'United Kingdom',
  'United States',
  'Canada',
  'Germany',
  'France',
  'Netherlands',
  'Italy',
  'Spain',
  'Portugal',
  'Ireland',
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'India',
  'China',
  'Australia',
];

const kDefaultCountry = 'Ghana';
